Sprint 3
lizgam/middle.messenger.praktikum.yandex pull request #3
Opened 2022-07-07 05:34 UTC by lizgam

2022-07-07 06:06 UTC, ivan-infro commented
Необходимо написать тесты для шаблонизатора, роутера, компонента, модуля отправки запросов. Обратите внимание, что eslint и stylelint тоже должны запускаться корректно и не выдавать ошибок.

2022-07-07 06:12 UTC, ivan-infro commented
Независимо от выбранного чата, отображаются одни и те же сообщения

2022-07-07 06:19 UTC, ivan-infro commented
При обновлении страницы с определённым URL должна отображаться та же самая страница. То есть если пользователь зашел, например, на страницу регистрации и обновил её, она загрузится снова.

2022-07-07 06:32 UTC, ivan-infro requested changes

2022-07-07 06:32 UTC, ivan-infro commented on src/components/Dialog/dialog.ts
> +                            inputType="number"
Тут необходимо использовать API поиска пользователя по логину https://ya-praktikum.tech/api/v2/swagger/#/Users/post_user_search

2022-07-07 06:32 UTC, ivan-infro commented on src/api/authAPI.ts
> +        return this.http.post("/signup", { data, headers: { "Content-Type": "application/json" } });
Заголовок "Content-Type": "application/json" добавляется практически к каждому запросу, его можно вынести в BaseAPI, либо добавить новые методы postJSON/getJSON/...

2022-07-07 06:32 UTC, ivan-infro commented on src/components/Card/card.ts
> +        if (props.card && props.selectedCard) {
Лучше придерживаться единого стиля и использовать переменные props через деструктуризацию объекта

2022-07-07 06:32 UTC, ivan-infro commented on src/components/Dialog/dialog.ts
> +interface DialogProps {
Для описание состояния и свойств (пропсов) лучше использовать type, подробнее почитать можно здесь: https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/basic_type_example#tldr

2022-07-07 06:32 UTC, ivan-infro commented on src/components/Dialog/dialog.ts
> +                const userId = (this.element?.querySelector("[name=\"userId\"]") as HTMLInputElement
Старайтесь не использовать принудительное приведение типов (as), т.к. это может привести к ошибкам. В данном случае удобнее использовать Generic type: this.element?.querySelector<HTMLInputElement>

2022-07-07 06:32 UTC, ivan-infro commented on src/services/chats.ts
> +        const socketURI = `wss://ya-praktikum.tech/ws/chats/${payload.userId}/${payload.chatId}/${chatToken.token}`;
Адрес ya-praktikum.tech уже вынесен в константу, тут лучше переиспользовать ее же (или завести новую)

2022-07-07 06:32 UTC, ivan-infro commented on src/services/chats.ts
> +            let parsedData: any[] = JSON.parse(event.data);
Данным от сервера, как и данным от пользователя, всегда лучше немножко не доверять :) Данный JSON.parse рекомендую обернуть в try ... catch, чтобы корректно обрабатывать возможные ошибки парсинга

2022-07-07 06:32 UTC, ivan-infro commented on src/utilities/helpers.ts
> +type PlainObject<T = any> = {
Не храните закомментированный код в репозитории, это усложняет чтение другими разработчиками

2022-07-07 06:52 UTC, lizgam commented
> Необходимо написать тесты для шаблонизатора, роутера, компонента, модуля отправки запросов. Обратите внимание, что eslint и stylelint тоже должны запускаться корректно и не выдавать ошибок.

нас предупредили в начале спринта, что он объемный и тесты можно перенести на 4 спринт (так сказали на вебинаре по архитектуре)

2022-07-07 07:02 UTC, lizgam commented
> 



> При обновлении страницы с определённым URL должна отображаться та же самая страница. То есть если пользователь зашел, например, на страницу регистрации и обновил её, она загрузится снова.
Подскажите пожалуйста, для какой страницы это не работает (или шаги для воспроизведения). Я заметила проблему только страницы регистрации, но может что-то еще пропустила. И кажется что-то с нетлифаем - он просто не позволяет перезагружать страницы...

2022-07-07 07:16 UTC, lizgam commented on src/components/Dialog/dialog.ts
> +                const userId = (this.element?.querySelector("[name=\"userId\"]") as HTMLInputElement
если убрать `as`, то VSCode выводит предупреджение. Как поступать в этом случае?
...и я делала так по примеру кода наставников ( https://github.com/noveogroup-amorgunov/practicum-screencasts/blob/a0fce9254bc8eddd0a0ea585296f207b5debc964/sprint-3-single-page-application/src/pages/login/login.ts#L37)
Как, подскажите пожалуйста, мне тогда можно избежать использования AS, чтоб не подсвечивалось это предупреждением?

2022-07-07 07:43 UTC, ivan-infro commented on src/components/Dialog/dialog.ts
> +                const userId = (this.element?.querySelector("[name=\"userId\"]") as HTMLInputElement
> если убрать as, то VSCode выводит предупреджение. Как поступать в этом случае?
Это как-раз отличный пример, когда приведение типа "замалчивает" возможную ошибку)
Вот так
```
                const userId = this.element?.querySelector<HTMLInputElement>("[name=\"userId\"]")?.value;
                if (!userId) {

```
будет надеждней

2022-07-07 07:44 UTC, ivan-infro commented on src/components/Dialog/dialog.ts
> +                const userId = (this.element?.querySelector("[name=\"userId\"]") as HTMLInputElement
querySelector может вернуть null, тогда обращение null.value упадет с ошибкой

2022-07-07 08:23 UTC, ivan-infro commented
> > При обновлении страницы с определённым URL должна отображаться та же самая страница. То есть если пользователь зашел, например, на страницу регистрации и обновил её, она загрузится снова.
> 
> Подскажите пожалуйста, для какой страницы это не работает (или шаги для воспроизведения)? Я заметила проблему только страницы регистрации ( я пользовательский сценарий так поняла), но может что-то еще пропустила. И кажется что-то с нетлифаем - он просто не позволяет перезагружать страницы...

Если запускать `npm run start` (и на netlify, но он не в счет), то не работает обновление страницы. В dev все хорошо

2022-07-08 05:53 UTC, lizgam commented on src/components/Card/card.ts
> +        if (props.card && props.selectedCard) {
для консистентности сделала остальные методы/проперти так же

2022-07-09 00:10 UTC, merged